#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

echo -e "${SCRIPT}: BEGIN `date` (OK)"

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo -e "${SCRIPT}: WARNING - This script is designed for Linux. Skipping installation on macOS."
  exit 1
fi

echo -e "${SCRIPT}: apt update; apt upgrade..."
sudo apt-get update -y
sudo apt-get upgrade -y

# HACK BEGIN
# FIX BROKEN INSTALL OF  grub-efi-amd64-signed
sudo rm /var/lib/dpkg/info/grub*
sudo dpkg --configure -a
# HACK END

${DIR}/install-node 24 &&
${DIR}/update-npm 11 &&
${DIR}/install-ripgrep &&
${DIR}/install-audio-tools &&
npm install && 
echo -e "${SCRIPT}: END `date` (OK)"
